parameters:
    netgen_social_connect.default.facebook_id: ~
    netgen_social_connect.default.twitter_id: ~
    netgen_social_connect.default.linkedin_id: ~
    netgen_social_connect.default.google_id: ~