parameters:
    netgen_social_connect.default.facebook.id: ~
    netgen_social_connect.default.twitter.id: ~
    netgen_social_connect.default.linkedin.id: ~
    netgen_social_connect.default.google.id: ~