facebook_login:
    pattern: /login/login_facebook
    defaults: { _controller: ezpublish.security.controller:loginAction }

google_login:
    pattern: /login/login_google
    defaults: { _controller: ezpublish.security.controller:loginAction }

twitter_login:
    pattern: /login/login_twitter
    defaults: { _controller: ezpublish.security.controller:loginAction }

linkedin_login:
    pattern: /login/login_linkedin
    defaults: { _controller: ezpublish.security.controller:loginAction }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

netgen_social_connect_ez:
    pattern: /ezconnect/{resource_name}
    defaults: { _controller: netgen.social_connect.controller.connect:connectUser }

netgen_social_disconnect_ez:
    pattern: /ezdisconnect/{resource_name}
    defaults: { _controller: netgen.social_connect.controller.connect:disconnectUser }
