parameters:
    hwi_oauth.resource_owner.facebook.class: Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\FacebookResourceOwner
    hwi_oauth.resource_owner.twitter.class: Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\TwitterResourceOwner
    hwi_oauth.resource_owner.google.class: Netgen\Bundle\EzSocialConnectBundle\OAuth\ResourceOwner\GoogleResourceOwner

services:
    netgen.social_connect.oauth_user_provider:
        class: Netgen\Bundle\EzSocialConnectBundle\OAuth\eZUserProvider
        parent: ezpublish.security.user_provider
        arguments:
            - @netgen.social_connect.helper
        calls:
            - [setMergeAccountsFlag, ["$merge_social_accounts;netgen_social_connect$"]]

    netgen.social_connect.helper:
        class: Netgen\Bundle\EzSocialConnectBundle\Helper\SocialLoginHelper
        arguments:
            - @ezpublish.api.repository
            - @doctrine.orm.entity_manager
            - @ezpublish.config.resolver
            - @ezpublish.field_helper
            - @?logger
        calls:
            - [setFirstName,    ["$first_name;netgen_social_connect$"]]
            - [setLastName,     ["$last_name;netgen_social_connect$"]]
            - [setProfileImage, ["$profile_image;netgen_social_connect$"]]
        lazy: true

    netgen.social_connect.controller.connect:
        class: Netgen\Bundle\EzSocialConnectBundle\Controller\ConnectController
        parent: ezpublish.controller.base
